### ISSUE TITLE
new paper

### ISSUE THREAD

**Issue by ahkarami** [jinwchoi/Jinwoo-Computer-Vision-and-Machine-Learing-papers-to-read#2]
Dear @jinwchoi,
You can add our new paper to your awesome list. 
[Temporal 3D ConvNets: New Architecture and Transfer Learning for Video Classification](https://arxiv.org/abs/1711.08200) 
Thank you

**Comment by jinwchoi** [comment]
Added it. FYI, this repo is not actually an "awesome" list yet. Trying to make it "awesome", but need to work on something more to be included in the actual "awesome" list. :)
