### ISSUE TITLE
About skeleton-based action recognition

### ISSUE THREAD

**Issue by WWKy** [jinwchoi/Jinwoo-Computer-Vision-and-Machine-Learing-papers-to-read#24]
Hi.
All papers about skeleton-based action recognition are not in the list? Like ST-GCN https://github.com/yysijie/st-gcn

**Comment by jinwchoi** [comment]
Good point! You are very welcome to make modifications of this repo and submit a PR. :)

**Comment by WWKy** [comment]
OK. I'm doing this.
