### ISSUE TITLE
VTT: Visual Object Tagging Tool

### ISSUE THREAD

**Issue by escorciav** [jinwchoi/Jinwoo-Computer-Vision-and-Machine-Learing-papers-to-read#28]
Hi!

Could you please consider to add VTT?

[VTT](https://github.com/microsoft/VoTT) is another annotation tool. It seems similar to VATIC with more recent tools (electron, tensorflow-js).

Cheers,
Víctor

**Comment by jinwchoi** [comment]
Hi Victor,

Looks good! Feel free to submit a pull request about the two tools you mentioned.
