### ISSUE TITLE
New CVPR 2018 Paper

### ISSUE THREAD

**Issue by ahkarami** [jinwchoi/Jinwoo-Computer-Vision-and-Machine-Learing-papers-to-read#9]
@jinwchoi, 
You can add our new paper to your list:
[Temporal 3D ConvNets using Temporal Transition Layer](http://openaccess.thecvf.com/content_cvpr_2018_workshops/papers/w19/Diba_Temporal_3D_ConvNets_CVPR_2018_paper.pdf)
Thank you.

**Comment by jinwchoi** [comment]
You can submit a PR which includes the paper.
